name: TestTimezone
env:
  TZ: Europe/Paris            # timezone of environment
on:
  workflow_dispatch:
#      inputs:
#      logLevel:
#        description: 'Log level'     
#        required: true
#        default: 'warning'
#      tags:
#        description: 'Test scenario tags'
#  push:
#    branches:
#      - master
#    paths:
#      - 'check_timezone'
#  schedule:
    # ┌───────────── minute (0 - 59)
    # │ ┌───────────── hour (0 - 23)
    # │ │ ┌───────────── day of the month (1 - 31)
    # │ │ │ ┌───────────── month (1 - 12)
    # │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
    # │ │ │ │ │                                   7 is also Sunday on some systems)
    # │ │ │ │ │
    # │ │ │ │ │
    # * * * * * <command to execute>
    #- cron:  '30 7 * * 1,2,3,4,5'      # weekly - every monday-fridayy at 7:30 UTC = 8:30 CET
    #- cron:  '55 5 * * 5'              # weekly - every friday at 5:55 UTC
#     - cron:  '* * * * *'               # every minute

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
 #     - uses: actions/checkout@v3
 #     - name: Check timezone
 #       run: |
 #         echo "Current time zone: $(date +%Z)"
 #         echo "Current date: $(date)"
 #         echo "Log level: ${{ github.event.inputs.logLevel }}"
 #         echo "Tags: ${{ github.event.inputs.tags }}" 
      - run: bats -v
