name: TestTimezone
env:
  TZ: Europe/Paris            # timezone of environment
on:
  push:
    branches:
      - master
    paths:
      - 'check_timezone'
  schedule:
    - cron:  '30 7 * * 1,2,3,4,5'     # weekly - every monday-fridayy at 7:30 UTC = 8:30 CET
    #- cron:  '55 5 * * 5'    # weekly - every friday at 5:55 UTC
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check timezone
        run: |
          echo "Current time zone: $(date +%Z)"
          echo "Current date: $(date)"
